#!/bin/bash
###---------- ALIASES ----------###

randomman(){
	man -k . | awk '{print $1}'  | sk --height 40% --reverse | xargs -r man
}

uu(){
	unset HISTFILE 
	PROMPT='󰗹 %B%F{10} %B%F{015}%~%B%F{006} 󰅂%b%F{015} '
	clear
}

bulkrename() {
    tmpfile_old="$(mktemp)"
    tmpfile_new="$(mktemp)"

    [ -n "$fs" ] && fs=$(basename -a $fs) || fs=$(\ls)

    echo "$fs" > "$tmpfile_old"
    echo "$fs" > "$tmpfile_new"
    $EDITOR "$tmpfile_new"

    [ "$(wc -l < "$tmpfile_old")" -eq "$(wc -l < "$tmpfile_new")" ] || { rm -f "$tmpfile_old" "$tmpfile_new"; exit 1; }

    paste "$tmpfile_old" "$tmpfile_new" | while IFS="$(printf '\t')" read -r src dst
    do
        [ "$src" = "$dst" ] || [ -e "$dst" ] || mv -- "$src" "$dst"
    done

    rm -f "$tmpfile_old" "$tmpfile_new"
}

alias cpy="xclip -selection c"
alias h="cat ~/.cache/zsh/history | cut -c 8- | sort | uniq |sk | tr '\\n' ' ' | cpy"

alias mm="randomman" 
alias update="sudo pacman -Syyuu"
alias p="sudo pacman"

alias ip="ip -color=auto"
#alias  l="eza  --color=always --group-directories-first"
#alias ls="eza  --color=always --group-directories-first"
#alias ll="eza -la  --color=always --group-directories-first"
#alias la="eza -a   --color=always --group-directories-first"
alias  l="eza --icons=always --color=always --group-directories-first"
alias ls="eza --icons=always --color=always --group-directories-first"
alias ll="eza -la --icons=always --color=always --group-directories-first"
alias la="eza -a  --icons=always --color=always --group-directories-first"

alias ssn="sudo shutdown now"
alias gc="git clone"
alias ez="nvim ~/.config/zsh/.zshrc"
alias ezp="nvim $HOME/.config/zsh/.zprofile"
alias xi="nvim ~/.config/x11/xprofile"
alias wget="wget -c --hsts-file $HOME/.config/wget/wget-hsts"
alias cat="bat --theme ansi"
alias vim="nvim"
alias v="nvim"
alias cd="z"
alias ff="yazi"
alias nb="newsboat"
alias ka="killall"
alias grep="grep --color=always"
alias tree="tree -C | less"
alias dwmake="sudo make clean install;xdotool key super+shift+r"

alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="trash -v" \
	bc="bc -ql" \
	rsync="rsync -vrPlu" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ytt="yt --skip-download --write-thumbnail" \
	ffmpeg="ffmpeg -hide_banner" 

###---------- ARCHIVE EXTRACT ----------###

ex ()
{
    if [ -f $1 ] ; then
      case $1 in
        *.tar.bz2)   tar xjf $1   ;;
        *.tar.gz)    tar xzf $1   ;;
        *.bz2)       bunzip2 $1   ;;
        *.rar)       unrar x $1   ;;
        *.gz)        gunzip $1    ;;
        *.tar)       tar xf $1    ;;
        *.tbz2)      tar xjf $1   ;;
        *.tgz)       tar xzf $1   ;;
        *.zip)       unzip $1     ;;
        *.Z)         uncompress $1;;
        *.7z)        7za e x $1   ;;
        *.deb)       ar x $1      ;;
        *.tar.xz)    tar xf $1    ;;
        *.tar.zst)   unzstd $1    ;;
        *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}
