#!/bin/sh

# Tags configuration

for i in $(seq 1 9)
do
    tags=$((1 << ("$i" - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super "$i" set-focused-tags $tags
    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift "$i" set-view-tags $tags
    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control "$i" toggle-focused-tags $tags
    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control "$i" toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
#riverctl map normal Super Space toggle-float

# Set background and border color
riverctl background-color 0x000000
riverctl border-color-focused 0x537453

#riverctl border-color-unfocused 0x586e75
riverctl border-color-unfocused 0x888888
riverctl border-width 3

# Set keyboard repeat rate
riverctl set-repeat 50 200

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 2 -outer-padding 2 &

autostart="yambar mpd dunst"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done

riverctl spawn "xrdb -merge ~/.config/x11/xresources &"
riverctl spawn "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"

[ -z "$(pidof foot)" ] && riverctl spawn "foot --server &"
[ -z "$(pidof xdg-desktop-portal-wlr)" ] && riverctl spawn "/usr/lib/xdg-desktop-portal-wlr &"
[ -z "$(pidof xss-lock)" ] && riverctl spawn "xss-lock -- swaylock"
[ -z "$(pidof wbg)" ] && riverctl spawn "setbg"

. "/home/taimoor/.config/river/binds"
. "/home/taimoor/.config/river/input"
. "/home/taimoor/.config/river/rules"

scratchTag=$((1 << 20))
riverctl map normal Super 0 toggle-focused-tags $scratchTag
riverctl map normal Super+Shift 0 set-view-tags $scratchTag
riverctl spawn-tagmask $((((1 << 32) - 1) ^ scratchTag))
