bg_default: &bg_default {stack: [{background: {color: 44415aff}}, {underline: {size: 0, color: D8DEE9ff}}]}
bar:
  height: 24
  location: top
  background: 2E3440ff
  font: MesloLGS Nerd Font:pixelsize=18

  right:
    - backlight:
                   name: intel_backlight
                   content:
                     string: {text: "[󰖨 {percent}%]"}
    - script:
                   path: ~/.local/bin/statusbar/sb-nettraf
                   content: {string: {text: " [󱚶 {test}] "}}
    - cpu:
                   poll-interval: 2500
                   content:
                     map:
                       on-click:
                         left: "footclient -e htop"
                       conditions:
                         id < 0:
                           - string: {text: "[  {cpu}%] "}
    - pulse:
       content:
         map:
           on-click:
             left: "footclient -e pulsemixer"
             wheel-up: "wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%+"
             wheel-down: "wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%-"
           conditions:
             online:
               - string: {text: "[  {sink_percent}%] " }
    - battery:
                   name: BAT0
                   poll-interval: 1000
                   content:
                     map:
                       on-click:
                         right: "~/.config/yambar/scripts/actions battery"
                         left:  "footclient -e battop"
                         wheel-down: "brightnessctl set 5%-"
                         wheel-up: "brightnessctl set +5%"
                       conditions:
                         state == discharging:
                           string: {text: "[󰂁 {capacity}%] "}
                         state == charging:
                           string: {text: "[󰂄 {capacity}%] "}
                         state == full:
                           string: {text: "[󰁹 {capacity}%] "}

  left:
        - clock:
                   time-format: "%a %d %b %r"
                   content:
                     string: {text: "[󱑀 {time}]"}

  center:
    - river:
        anchors:
          - base: &river_base
              left-margin: 8
              right-margin: 8
              default: {string: {text: }}
              conditions:
                id == 1: {string: {text: 1}}
                id == 2: {string: {text: 2}}
                id == 3: {string: {text: 3}}
                id == 4: {string: {text: 4}}
                id == 5: {string: {text: 5}}
                id == 6: {string: {text: 6}}
                id == 7: {string: {text: 7}}
                id == 8: {string: {text: 8}}

        content:
          map:
            on-click:
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            conditions:
              state == urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: D08770ff}}
              state == focused:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == visible && ~occupied:
                map:
                  <<: *river_base
              state == visible && occupied:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == unfocused:
                map:
                  <<: *river_base
              state == invisible && ~occupied: {empty: {}}
              state == invisible && occupied:
                map:
                  <<: *river_base
                  deco: {underline: {size: 0, color: ea6962ff}}

