# Colors (Hyper)

# Default colors
[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.cursor]
text = '#F81CE5'
cursor = '#ffffff'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#fe0100'
green   = '#33ff00'
yellow  = '#feff00'
blue    = '#0066ff'
magenta = '#cc00ff'
cyan    = '#00ffff'
white   = '#d0d0d0'

# Bright colors
[colors.bright]
black   = '#808080'
red     = '#fe0100'
green   = '#33ff00'
yellow  = '#feff00'
blue    = '#0066ff'
magenta = '#cc00ff'
cyan    = '#00ffff'
white   = '#FFFFFF'# Source https//github.com/zatchheems/tokyo-night-alacritty-theme

[font]
size = 12

[font.bold]
family = "Cousine Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Cousine Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Cousine Nerd Font"
style = "Italic"

[font.normal]
family = "Cousine Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 50000

[window]
opacity = 0.8
